---
services: docker

env:
  - distro: centos7

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
