- hosts: confluence
  gather_facts: true

  environment: "{{proxy_env}}"

  roles:
    - role: ansiblebit.oracle-java
      become: yes
      tags: java
    - role: alvistack.confluence
      become: yes
      tags: confluence
