- import_playbook: database.yml
- import_playbook: www.yml
- import_playbook: confluence.yml
- import_playbook: jira.yml
- hosts: all
  become: yes
  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
      become: yes
